name = "backend"
main = "src/index.ts"
compatibility_date = "2024-10-02"
compatibility_flags = [ "nodejs_compat" ]

 [vars]
 DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiMDJmY2NkODktYzgyNC00YjIzLWJjYzAtZDA3NzgxNTc3YmIzIiwidGVuYW50X2lkIjoiNGFlNDAyOGY1MzVjYTYzMjFkNDZkNmI0YjkwNjdmOThjZmJmOWQzM2NiYjU4NzhmZWEwYzg1NWYxZTEwZDI1YSIsImludGVybmFsX3NlY3JldCI6IjExZDRmMWMxLTA2YTgtNDVmMS04MTE1LTgwMDg5ZmYxYjg0YiJ9.7fahvOkoZcFv0Qv_5GZtryekw0tbDEoHOrl3IL9yGCo"
 JWT_SECRET = "India"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"